### ISSUE TITLE
Enable 'copy seed' button without uploading bin file beforehand

### ISSUE THREAD

**Issue by HexTree** [ProGrammar-R/ProGrammar-R.github.io#56]
Currently the 'copy seed' button is greyed out until you've uploaded a bin file and randomised.

I think it would be ideal to be able to create a seed link just to share with others (e.g. before a rando match) without the requirement of going through the uploading steps first.

**Comment by ProGrammar-R** [comment]
@HexTree I'm about to implement this, but I want to be sure that this meets your needs. Right now the seed is copied to the clipboard; will CurryBot be able to work with that?

As an aside, seeds generated before randomizing won't have a checksum since there's no data to check, which makes them less suitable for tournament races.

**Comment by ProGrammar-R** [comment]
Implemented in 73efc33. Sorry for the wait.
